In [4]:
a = [[2, 4, 6], [3, 6, 9], [4, 8, 12]]

In [7]:
a[1][2]

9

In [8]:
a[2][2]

12

In [11]:
a[0:2]

[[2, 4, 6], [3, 6, 9]]

In [16]:
a[1:2:1]

[[3, 6, 9]]

Numpy array Slicing 
===============

In [18]:
import numpy as np

In [20]:
arr = np.array([[1, 2, 3, 4],[5,6,7,8],[9,10,11,12]])

In [21]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### This arr.shape gives you the shape of array

In [23]:
arr.shape

(3, 4)

In [25]:
arr[2][3]

12

In [26]:
arr[1, 2]

7

In [27]:
arr[:1]

array([[1, 2, 3, 4]])

In [28]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr[1:,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr[1:,:2]

array([[ 5,  6],
       [ 9, 10]])

In [36]:
arr[0:3,:1]

array([[1],
       [5],
       [9]])

In [42]:
arr[0:3, 1:2]

array([[ 2],
       [ 6],
       [10]])

In [45]:
arr[0:3, 2:3]

array([[ 3],
       [ 7],
       [11]])

In [47]:
arr[0:3, 3:4]

array([[ 4],
       [ 8],
       [12]])

In [54]:
arr[1, 1:3]

array([6, 7])

Elementary Image Processing
===